[package]
name = "els"
version = "0.1.0"
authors = ["Erik Rimskog <erik.rimskog@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
opt-level = "z"
strip = true

[dependencies]
libc = "^0.2.97"
lazy_static = "^1.4.0"
