#!/bin/bash

# This is a wrapper around deluge that perform some monitoring tasks that isn't possible
# by default.

exec deluge-cli \
     -vv \
     foreach \
     --spawn-deluge \
     --loop 1min \
     just-finished send-notification "Torrent complete" , \
     is-duplicated send-notification "Duplicated files" any foreach-file \( print-duplicate \) , \
     \( download-rate-le 5min 0b/s active-for-ge 5min or download-rate-le 5min 50kb/s writing-for-ge 5min \) queue-bottom printf 'Got stale {t}'

