#!/bin/sh
user=$1
acpi -b | awk -F'[,:%]' '{print $2, $3}' | {
    read -r status capacity

    if [ "$status" = Discharging ]; then
        if [ "$capacity" -lt 20 ]; then
            if [ -n "$user" ]; then
                notify-send 'Battery-checker' 'low battery warning, force suspend on 10%'
		logger "battery low warning"
            fi
        elif [ "$capacity" -lt 11 ]; then
            if [ -n "$user" ]; then
                notify-send 'Battery-checker' 'CRITICAL! SUSPENDING'
		logger "battery critical warning"
            else
		logger "suspending due to critically low battery"
                systemctl suspend
            fi
        fi
    fi
}
