#!/bin/bash

if ! which cowthink || ! which fortune; then
    exit;
fi &>/dev/null;

rand_file="$(ls -1 /usr/share/cows | shuf -n 1)"
rand_expr="$(echo -e "-b\n-d\n-g\n-p\n-s\n-t\n-w\n-y\n" | shuf -n 1)"
fort="$(fortune -as)"
# echo "$rand_file"
# echo "$rand_expr"
# echo "$fort"

if [[ "$rand_expr" ]]; then
    echo "$fort" | cowthink "$rand_expr" -f "$rand_file"
else
    echo "$fort" | cowthink -f "$rand_file"
fi;
