#+STARTUP: overview

* Programming
** binary search
[[https://stackoverflow.com/a/33463489][stackoverflow]]

Easy way to find e.g. largest value smaller than some given value in a
sorted list.

Define both limits l and r to be inclusive.
Let A be the array and N some number to search for.
A[i] < N for all i < l and
A[i] >= N for all i > r.
Equal sign can be on either side, depending on desired outcome.
* git
** pruning branches
Remove remote branches that no longer exists:
#+BEGIN_SRC sh
git remote prune origin
git fetch --prune
#+END_SRC

List branches that have been merged:
#+BEGIN_SRC sh
git branch --merged
#+END_SRC
** merge strategies
*** ignore others
[[https://git-scm.com/docs/merge-strategies][docs]]
To rebase unto master and solve all merge conflicts by taking our changes.
The role of ours and theirs switch places in rebases.
#+BEGIN_SRC sh
git rebase -X theirs master
#+END_SRC
*** similarity index
To specify how similar two files has to be to be considered a rename
instead of two additions or something. Default is 50%.
#+BEGIN_SRC sh
git merge -Xrename-threshold=10% master
#+END_SRC
** move a branch
Move BRANCH to START-POINT, or in other words create BRANCH at
START-POINT while overriding BRANCH if it already exists.
#+BEGIN_SRC sh
git branch -f BRANCH START-POINT
#+END_SRC
** log
#+BEGIN_SRC sh
git log branch1 branch2 branch3
git log --date-order
git log --topo-order # default in --graph
git log A...B # commits reachable from either branch but not both
git log A..B # reachable from B but not A
#+END_SRC

--topo-order
#+begin_quote
Show no parents before all of its children are shown, and avoid
showing commits on multiple lines of history intermixed.
#+end_quote

*** first parent
Reveal "true history" of master by ignoring feature branch commits, if
no fast-forwarding on the master has occured (I think).
#+BEGIN_SRC sh
git log --first-parent
#+END_SRC
** diff
#+BEGIN_SRC sh
git diff A...B
# <=>
git diff $(git-merge-base A B) B
#+END_SRC
** local gitignore
~.git/info/exclude~
samma syntax som vanliga .gitignore

** fast-forward branch without checking out
[[https://stackoverflow.com/a/17722977][src]]
#+BEGIN_SRC bash
git fetch origin master:master
#+END_SRC
* swapfiles
** show available
To show available swap
#+BEGIN_SRC bash
free
swapon --show
#+END_SRC
** create one
[[https://wiki.archlinux.org/index.php/Swap#Swap_file_creation][archwiki]]

#+BEGIN_SRC bash
fallocate -l 1G /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
#+END_SRC
Good to have the owner as root?

Add the following to ~/etc/fstab~
#+BEGIN_SRC
/swapfile none swap defaults 0 0
#+END_SRC

** reduce swappiness
[[https://wiki.archlinux.org/index.php/Swap#Swappiness][archwiki]]
Add a file ~/etc/sysctl.d/99-swappiness.conf~ and add:
#+BEGIN_SRC 
vm.swappiness=0
#+END_SRC
Check the current value with =sysctl vm.swappiness=.

This sets the kernel's preference to swap file-backed pages (basically
the filesystem cache) and anonymous pages. A value of 0 signals a
strong preference to swap out file-backed instead of anonymous.

Swapping is only performed when RAM is pretty much full (I think).
[[https://www.howtogeek.com/449691/what-is-swapiness-on-linux-and-how-to-change-it/][source]]

A low value will increase application responsiveness because the
kernel is not swapping out code ([[https://rudd-o.com/linux-and-free-software/tales-from-responsivenessland-why-linux-feels-slow-and-how-to-fix-that][source]]).

* GTK-theme
[[https://www.gnome-look.org/p/1247600/][Adwaita-dark]]
* clipmenud
clipmenud will poll the X server (?) if ~clipnotify~ is not installed.
* systemd
** /etc/systemd/journald.conf
Limit log size:
#+BEGIN_SRC
SystemMaxUse=500M
#+END_SRC
** /etc/systemd/logind.conf
Kill all processes in session when logging out:
#+BEGIN_SRC
KillUserProcesses=yes
#+END_SRC

Lid close:
#+BEGIN_SRC
HandleLidSwitch=suspend
HandleLidSwitchDocked=ignore
#+END_SRC
Docked is when an external display is connected.

Don't do anyhting on =power= key
#+BEGIN_SRC
HandlePowerKey=ignore
#+END_SRC
* faillock
To control how many login attempts is needed for locking an account
and the timeout, edit: ~/etc/security/faillock.conf~. Can reset
manually with the ~faillock~ command.
* keyboard
Sets the keyboard layout permanently in xorg.
#+BEGIN_SRC sh
localectl set-x11-keymap se '' nodeadkeys
#+END_SRC
* mouse
** speed
Place these in ~/etc/X11/xorg.conf.d/~
Set mouse to flat profile and max speed.
#+BEGIN_SRC
Section "InputClass"
	Identifier "My Mouse"
	Driver "libinput"
	MatchIsPointer "yes"
	MatchProduct "Logitech M720 Triathlon"
	Option "AccelProfile" "flat"
	Option "AccelSpeed" "1"
EndSection
#+END_SRC

Same but for a touchpad.
#+BEGIN_SRC
Section "InputClass"
  Identifier "my touchpad settings"
  Driver "libinput"
  MatchIsTouchpad "yes"
  MatchProduct "ELAN0501:00 04F3:3060 Touchpad"
  Option "AccelSpeed" "0.8"
  Option "NaturalScrolling" "yes"
  Option "AccelProfile" "flat"
  Option "Tapping" "on"
EndSection
#+END_SRC

* DNS
ändra i ~/etc/resolvconf.conf~ för att skriva över med nya dnser.
ändra med =nm-applet= för att lägga till backups.

* Graphical sudo
Vissa GUI-program vill autentisera för att göra något sudo.
Görs via polkit elr nåt. Starta denna vid startup:
#+BEGIN_SRC sh
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
#+END_SRC

* Dropbox
fixa så att systemd-servicen inte startar om dropbox i en oändlig loop:
https://wiki.archlinux.org/title/dropbox#Prevent_automatic_updates

TL;DR från länken:
Få dropbox att sluta autouppdatera sig med:
#+BEGIN_SRC sh
rm -rf ~/.dropbox-dist
install -dm0 ~/.dropbox-dist
#+END_SRC

* Kernel upgrades and modules
[[https://github.com/saber-nyan/kernel-modules-hook][github]]
#+BEGIN_SRC sh
pacman -Syu kernel-modules-hook
#+END_SRC

* Bash
** Nice script options
#+BEGIN_SRC bash
set -e # exit on first command failure
set -u # exit when an unset variable is used
set -x # print every command that is run, prefixed with PS4
set -o pipefail # the whole pipe contributes to the exit status, not only the last command
shopt -s lastpipe # the last thing in a pipe doesn't run in a subshell
shopt -s failglob # globs that doesn't match fail the command
#+END_SRC
