#+STARTUP: overview

* Programming
** binary search
[[https://stackoverflow.com/a/33463489][stackoverflow]]

Easy way to find e.g. largest value smaller than some given value in a
sorted list.

Define both limits l and r to be inclusive.
Let A be the array and N some number to search for.
A[i] < N for all i < l and
A[i] >= N for all i > r.
Equal sign can be on either side, depending on desired outcome.
** calculate the lexicographically next bit permutation
[[http://graphics.stanford.edu/~seander/bithacks.html#NextBitPermutation][link]]
** linking
When building, ~ld~ will use flags and ~LD_RUN_PATH~.
When executing, ~ld.so~ will look at ~LD_LIBRARY_PATH~, ~LD_PRELOAD~ and the included ~rpath~.
See ~man ld.so~.
* Tips for git
** pruning branches
Remove remote branches that no longer exists:
#+BEGIN_SRC sh
git remote prune origin
git fetch --prune
#+END_SRC

List branches that have been merged:
#+BEGIN_SRC sh
git branch --merged
#+END_SRC
** merge strategies
*** ignore others
[[https://git-scm.com/docs/merge-strategies][docs]]
To rebase unto master and solve all merge conflicts by taking our changes.
The role of ours and theirs switch places in rebases.
#+BEGIN_SRC sh
git rebase -X theirs master
#+END_SRC
*** similarity index
To specify how similar two files has to be to be considered a rename
instead of two additions or something. Default is 50%.
#+BEGIN_SRC sh
git merge -Xrename-threshold=10% master
#+END_SRC
** move a branch
Move BRANCH to START-POINT, or in other words create BRANCH at
START-POINT while overriding BRANCH if it already exists.
#+BEGIN_SRC sh
git branch -f BRANCH START-POINT
#+END_SRC
** log
#+BEGIN_SRC sh
git log branch1 branch2 branch3
git log --date-order
git log --topo-order # default in --graph
git log A...B # commits reachable from either branch but not both
git log A..B # reachable from B but not A
#+END_SRC

--topo-order
#+begin_quote
Show no parents before all of its children are shown, and avoid
showing commits on multiple lines of history intermixed.
#+end_quote

*** first parent
Reveal "true history" of master by ignoring feature branch commits, if
no fast-forwarding on the master has occured (I think).
#+BEGIN_SRC sh
git log --first-parent
#+END_SRC
** diff
#+BEGIN_SRC sh
git diff A...B
# <=>
git diff $(git-merge-base A B) B
#+END_SRC
** local gitignore
=.git/info/exclude=
samma syntax som vanliga .gitignore

** fast-forward branch without checking out
[[https://stackoverflow.com/a/17722977][src]]
#+BEGIN_SRC bash
git fetch origin master:master
#+END_SRC
* Installing arch linux
** swapfiles
*** show available
To show available swap
#+BEGIN_SRC bash
free
swapon --show
#+END_SRC
*** create one
[[https://wiki.archlinux.org/index.php/Swap#Swap_file_creation][archwiki]]

#+BEGIN_SRC bash
fallocate -l 1G /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
#+END_SRC
Good to have the owner as root?

Add the following to =/etc/fstab=
#+BEGIN_SRC
/swapfile none swap defaults 0 0
#+END_SRC

*** reduce swappiness
[[https://wiki.archlinux.org/index.php/Swap#Swappiness][archwiki]]
Add a file =/etc/sysctl.d/99-swappiness.conf= and add:
#+BEGIN_SRC 
vm.swappiness=0
#+END_SRC
Check the current value with ~sysctl vm.swappiness~.

This sets the kernel's preference to swap file-backed pages (basically
the filesystem cache) and anonymous pages. A value of 0 signals a
strong preference to swap out file-backed instead of anonymous.

Swapping is only performed when RAM is pretty much full (I think).
[[https://www.howtogeek.com/449691/what-is-swapiness-on-linux-and-how-to-change-it/][source]]

A low value will increase application responsiveness because the
kernel is not swapping out code ([[https://rudd-o.com/linux-and-free-software/tales-from-responsivenessland-why-linux-feels-slow-and-how-to-fix-that][source]]).

** clipmenud
clipmenud will poll the X server (?) if =clipnotify= is not installed.
** systemd
*** /etc/systemd/journald.conf
Limit log size:
#+BEGIN_SRC
SystemMaxUse=500M
#+END_SRC
But the defaults are sensible.
*** /etc/systemd/logind.conf
Kill all processes in session when logging out:
#+BEGIN_SRC
KillUserProcesses=yes
#+END_SRC

Lid close:
#+BEGIN_SRC
HandleLidSwitch=suspend
HandleLidSwitchDocked=ignore
#+END_SRC
Docked is when an external display is connected.

Don't do anyhting on =power= key
#+BEGIN_SRC
HandlePowerKey=ignore
#+END_SRC
** faillock
To control how many login attempts is needed for locking an account
and the timeout, edit: =/etc/security/faillock.conf=. Can reset
manually with the ~faillock~ command.
** Configure Xorg
*** keyboard
**** layout
Sets the keyboard layout permanently in xorg.
#+BEGIN_SRC sh
localectl set-x11-keymap se '' nodeadkeys
localectl set-keymap sv-latin1
#+END_SRC
**** repeat speed
Place this file at =/etc/X11/xorg.conf.d/10-my-keyboard.conf=
Repeat delay of 300ms and repeat rate of =1000/40 = 25hz=.
#+BEGIN_SRC
Section "InputClass"
 Identifier "my-keyboard"
 MatchIsKeyboard "on"
 Option "AutoRepeat" "300 40"
EndSection
#+END_SRC
*** mouse
Place these in =/etc/X11/xorg.conf.d/=
Set mouse to flat profile and max speed.
#+BEGIN_SRC
Section "InputClass"
	Identifier "My Mouse"
	Driver "libinput"
	MatchIsPointer "yes"
	MatchProduct "Logitech M720 Triathlon"
	Option "AccelProfile" "flat"
	Option "AccelSpeed" "1"
EndSection
#+END_SRC

Same but for a touchpad.
#+BEGIN_SRC
Section "InputClass"
  Identifier "my touchpad settings"
  Driver "libinput"
  MatchIsTouchpad "yes"
  MatchProduct "ELAN0501:00 04F3:3060 Touchpad"
  Option "AccelSpeed" "0.8"
  Option "NaturalScrolling" "yes"
  Option "AccelProfile" "flat"
  Option "Tapping" "on"
EndSection
#+END_SRC
*** monitors
To set resolution and orientations:
#+BEGIN_SRC
Section "Monitor"
    Identifier "DisplayPort-0"
    Option "Primary" "true"
    Option "PreferredMode" "2560x1440"
EndSection

Section "Monitor"
    Identifier "DisplayPort-2"
    Option "RightOf" "DisplayPort-0"
    Option "Rotate" "left"
    Option "PreferredMode" "2560x1440"
EndSection
#+END_SRC
*** DPMS
Increase the screensaver timeout to 20 mins
#+BEGIN_SRC
Section "ServerFlags"
    Option "StandbyTime" "20"
    Option "SuspendTime" "20"
    Option "OffTime" "20"
    Option "BlankTime" "20"
EndSection
#+END_SRC
** DNS
ändra i =/etc/resolvconf.conf= för att skriva över med nya dnser.
ändra med ~nm-applet~ för att lägga till backups.

** Graphical sudo
Vissa GUI-program vill autentisera för att göra något sudo.
Görs via polkit elr nåt. Starta denna vid startup:
#+BEGIN_SRC sh
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
#+END_SRC

** Dropbox
fixa så att systemd-servicen inte startar om dropbox i en oändlig loop:
https://wiki.archlinux.org/title/dropbox#Prevent_automatic_updates

TL;DR från länken:
Få dropbox att sluta autouppdatera sig med:
#+BEGIN_SRC sh
rm -rf ~/.dropbox-dist
install -dm0 ~/.dropbox-dist
#+END_SRC

** Kernel upgrades and modules
[[https://github.com/saber-nyan/kernel-modules-hook][github]]
#+BEGIN_SRC sh
pacman -Syu kernel-modules-hook
#+END_SRC

** ext4
By default is 5% of the filesystem reserved for the super user, but that is not necessary
on a non-root partition imho. It can be changed on creation with the =-m= flag on
~mkfs.ext4~ or changed afterward with ~tune2fs~ (I think it is called).
** XDG dirs
Install =xdg-user-dirs= to create the documents folder and the like in home folders.
** Reflector
[[https://wiki.archlinux.org/title/Reflector][archwiki]]
Can start a timer to update the mirrors weekly.
This is my =/etc/xdg/reflector/reflector.conf=:
#+BEGIN_SRC
# Set the output path where the mirrorlist will be saved (--save).
--save /etc/pacman.d/mirrorlist

# Select the transfer protocol (--protocol).
--protocol https

# Select the country (--country).
# Consult the list of available countries with "reflector --list-countries" and
# select the countries nearest to you or the ones that you trust. For example:
--country SE,DK,DE,NO

# Use only the  most recently synchronized mirrors (--latest).
--latest 5

# Sort the mirrors by download rate (--sort).
--sort rate
#+END_SRC
** systemd-boot
[[https://wiki.archlinux.org/title/Systemd-boot][archwiki]]
Need to create entries manually.
** NFS
*** server
Add this to =/etc/exports=
#+BEGIN_SRC
/home/erik/Videos/anime_cache 192.168.10.0/24(ro,insecure,all_squash)
#+END_SRC
and enable with ~systemctl enable nfs-server~.
*** client
in =/etc/fstab=
#+BEGIN_SRC
nas:/mnt/min-pool/data  /media/NAS      nfs     _netdev,defaults,users,relatime,exec,noauto,timeo=14    0 0
miu.local:/home/erik/Videos/anime_cache /media/miu      nfs     defaults,ro,soft,timeo=14,users,noauto,noatime,_netdev,x-systemd.automount,x-systemd.mount-timeout=10,x-systemd.idle-timeout=1min   0 0
nas.local:/mnt/min-pool/data    /media/nas      nfs     defaults,ro,soft,timeo=14,users,noauto,noatime,_netdev,x-systemd.automount,x-systemd.mount-timeout=3,x-systemd.idle-timeout=1min    0 0

#+END_SRC
** Systemd-networkd
*** Configure ethernet
Config files are placed in: =/etc/systemd/network=, the default ones are in =/usr/lib/systemd/network=.
To enable an ethernet port with DHCP and mDNS, create a file =50-hemma.network= or something:
#+BEGIN_SRC
[Match]
Name=eno1

[Network]
DHCP=yes
MulticastDNS=yes

[Link]
Multicast=yes
#+END_SRC

A static IP can be added with:
#+BEGIN_SRC
[Network]
DHCP=no
Address=192.168.10.42/24
Gateway=192.168.10.1
DNS=192.168.10.1
MulticastDNS=yes
#+END_SRC
*** Wake-on-LAN
Copy paste =99-default.link= and add ~WakeOnLan=magic~ in the link section and add a match
for a mac address in the match section. [[https://wiki.archlinux.org/title/Wake-on-LAN#systemd.link][archwiki]]
*** Disable ipv6
[[https://wiki.archlinux.org/title/IPv6#systemd-networkd_4][archwiki]]
#+BEGIN_SRC
[Network]
LinkLocalAddressing=ipv4
IPv6AcceptRA=no
#+END_SRC
** Add a user
No home directory will be created unless =-m= is given.
#+BEGIN_SRC bash
useradd -m -G wheel -s /usr/bin/zsh erik
#+END_SRC
** fsck
Mkinitcpio will run fsck on the root file system through its =fsck= hook. I don't think it
runs on the other filesystems, like home, so a 2 needs to be added in fstab for those,
+and a 0 for the root system so it doesn't get checked twice. I think that is how it works.+
It is safer to set it as 1 to make sure it is always run by /some/ mechanism, the redundancy
doesn't hurt.
** PC speaker as bell
Disable it by blacklisting it in =/etc/modprobe.d/nobeep.conf=
#+BEGIN_SRC
blacklist pcspkr
#+END_SRC
Unload it immediately with ~rmmod pcspkr~.
** Systemd-resolved
Simply enable the service AFTER creating a symlink:
#+BEGIN_SRC bash
ln -sf ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
#+END_SRC
** SSD trim
Simply enable the systemd fstrim timer.
** NTP
#+BEGIN_SRC sh
timedatectl set-ntp true
#+END_SRC
** Browser cache
Qutebrowser, and other chromium ones, probably firefox as well, write video cache data to
disk when streaming videos. I don't know why it doesn't use the RAM for that, but it can
be forced to do that anyways as explained [[https://wiki.archlinux.org/title/Chromium#Cache_in_tmpfs][here on archwiki]].

Simply remove that cache folder and add this entry to fstab and reboot:
#+BEGIN_SRC
tmpfs	/home/erik/.cache/qutebrowser	tmpfs	defaults,relatime,nosuid,nodev,size=2G	0 0
#+END_SRC
* Bash
** Nice script options
#+BEGIN_SRC bash
set -e # exit on first command failure
set -u # exit when an unset variable is used
set -x # print every command that is run, prefixed with PS4
set -o pipefail # the whole pipe contributes to the exit status, not only the last command
shopt -s lastpipe # the last thing in a pipe doesn't run in a subshell
shopt -s failglob # globs that doesn't match fail the command
#+END_SRC
