#!/bin/python
import sys
from bs4 import BeautifulSoup  # type: ignore
from typing import (
    Any,
    List,
    Tuple,
    Callable,
    Optional,
    TextIO,
    Iterator,
    TypeVar,
)
from urllib.parse import urlparse, urlunparse, ParseResult, parse_qs
from argparse import ArgumentParser, Namespace
from fcntl import flock, LOCK_EX
from pathlib import Path
from dataclasses import dataclass
from io import SEEK_END
from beautifulsoupUtils import unique_selector  # type: ignore

