#!/bin/bash

# https://trac.ffmpeg.org/wiki/Capture/Desktop#LosslessRecording
# Use `ffmpeg_resize screen.mkv 1080` or something to encode the large file into something
# more compact

exec ffmpeg \
     -f x11grab \
     -video_size 2560x1440 \
     -framerate 30 \
     -i "$DISPLAY" \
     -f pulse \
     -i alsa_output.pci-0000_00_1f.3.analog-stereo.monitor \
     -c:v libx264rgb \
     -crf 0 \
     -preset ultrafast \
     "$HOME/Videos/screen_$(date '+%Y-%m-%d#%H:%M:%S').mkv"
