#!/bin/bash

# TODO: flag to use something else than h265 eg for wmv
# TODO: flag to also re-encode audio stream

set -e

nodata=
# mp4 (I think) has some special data streams sometimes, that can't be copied.
if [[ $1 = --no-data ]]; then
    nodata=t
    shift
fi

basename=$(basename -- "$1")
dirname=$(dirname -- "$1")
ext=${basename##*.}
name=${basename%.*}
outputname=${dirname}/${name}_resized.${ext}

ffmpeg -i "$1" \
       -c copy \
       -map 0 \
       ${nodata:+ -map -0:d} \
       -c:v libx265 \
       -x265-params crf=18 \
       -preset veryfast \
       -filter:v scale=-2:${2:-720} \
       "$outputname"

mv "$outputname" "$1"

# Measurement results
# 4K -> 1080p
# 4.12G
#
# the best
# h265-crf18-veryfast-35min.mp4 1.24G
# h264-crf18-veryfast-18min.mp4 2G
# h264-crf18-fast-32min.mp4 2.33G
#
# bad
# h265-crf18-ultrafast-19min.mp4 910M
#
# really bad
# h265-crf23-ultrafast-17min.mp4 492M
# h265-crf28-ultrafast-16min.mp4 295M
