#!/bin/bash

set -e

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 file.flac [file.flac ...]"
    exit 1
fi

for f in "$@"; do
    asd=${f%.*}
    ffmpeg -i "$f" -codec:a libmp3lame -q:a 0 -c:v copy "${asd}.mp3"
done
