#!/bin/bash

cache=$HOME/.cache/sbcl-script$(realpath "$1")
if [ ! -x "$cache" ] || [ "$1" -nt "$cache" ]; then
    mkdir -p "$(dirname "$cache")" || exit 1
    sbcl --non-interactive \
         --load "$1" \
         --eval '(flet ((main () (main sb-ext:*posix-argv*)))
                   (sb-ext:save-lisp-and-die "'"$cache"'" :executable t :toplevel'" #'main))" \
         > "${cache}.log" 2>&1 || exit 1
fi

shift
exec "$cache" "$@"
