#!/bin/bash

# lock with blurred screenshot ################################################
# SCREEN='/tmp/screen.png'
# LOCK=~/.i3/lock.png

# scrot --delay 0 --quality 1 "$SCREEN"
# convert "$SCREEN" -scale 10% -scale 1000% "$SCREEN"
# convert "$SCREEN" "$LOCK" -gravity center -composite -matte "$SCREEN"
# i3lock -i "$SCREEN"
# rm "$SCREEN"

if ! pgrep -x i3lock; then
    res=$(xrandr | sed -nE 's/^.*primary ([0-9]+x[0-9]+).*$/\1/p')
    convert "$HOME/.lock" -resize "$res"\! "$HOME/themes/lock.png" -gravity center -composite -matte RGB:- | i3lock --tiling --raw "$res":rgb --image /dev/stdin
fi
