#!/bin/bash

# exists because of backwards compatability, use m4_start instead

# conky_start -n name -c [args] -t [tags]
# conky_start metro

if [[ $# -lt 1 ]]; then
    echo "arguments plz :(" >&2
    exit 1
fi

conkypath=
forconky=()
tags=()
current=

while [[ "$1" ]]; do
    case "$1" in
        -n)
            shift
            conkypath="$HOME/.config/conky/eriks_$1"
            if [[ ! -f $conkypath ]]; then
                echo "weird name" >&2
                exit 1
            fi
            ;;
        -c)
            current='c'
            ;;
        -t)
            current='t'
            ;;
        *)
            if [[ "$current" = "c" ]]; then
                forconky+=( "$1" )
            elif [[ "$current" = "t" ]]; then
                tags+=( "$1" )
            else
                echo "what is this?" >&2
                exit 1
            fi
            ;;
    esac
    shift
done

exec m4_start "$conkypath" conky "${forconky[@]}" -c -- "${tags[@]}"
