#!/bin/bash

set -ue

if [[ $# -ne 3 ]]; then
    echo wrong number of flags >&2
    exit 1
fi

config=$1
exe=$2
jailed=$3

if [[ -n $config ]]; then
    cd "$config"
    if ! slicer-gen; then
        notify-send 'Slicer-gen' 'Failed'
        exit 1
    fi
fi

cd

path=$(find "$HOME"/Games/slicers -name "${exe}*.AppImage")

if [[ $jailed == yes ]]; then
    netfilter=$(realpath "$HOME"/.config/slicer-firejail-netfilter.net)
    exec firejail --noprofile --net=enp4s0 --netfilter="$netfilter" --appimage "$path"
else
    exec "$path"
fi
