#!/bin/bash

levels=(0 $(seq 3200 -200 2000))
ind=0

function toggle {
    : $((ind+=$1))
    if [[ $ind -lt 0 ]]; then
        ind=0
    elif [[ $ind -ge ${#levels[@]} ]]; then
        ind=$((${#levels[@]}-1))
    fi

    if [[ ${levels[$ind]} -eq 0 ]]; then
        redshift -x &>/dev/null
    else
        redshift -PO ${levels[$ind]} &>/dev/null
    fi
}

trap 'toggle 1' USR1
trap 'toggle -1' USR2
trap 'kill $spid' EXIT

sleep infinity &
spid=$!
while ps -p $spid &>/dev/null; do
    wait $spid &>/dev/null
done
