#!/bin/bash

function printStatus {
    contents="$(cat "$HOME/.program_mode")"
    if [ "$contents" == "on" ]; then
        echo "P"
    elif [ "$contents" == "swe" ]; then
        # echo "%{F#ff6347}ÅÄÖ%{F-}"
        echo "ÅÄÖ"
    else
        echo ""
    fi
}


# buggar bara om vi har kört denna trap en gång
trap 'printStatus' USR1
# samma för SIGQUIT?
# trap 'trap "" TERM EXIT; kill $spid; trap - INT TERM; kill -INT $$' INT
trap 'kill $spid' EXIT

# doesn't kill itself with INT, but it should
# trap "exit" INT TERM
# trap "kill 0" EXIT

printStatus
sleep infinity & # SIGINT och SIGQUIT funkar inte på denna eftersom den är i background i ett icke-interaktivt bash-läge
spid=$!
# kill -0 $spid &>/dev/null
while ps -p $spid &>/dev/null; do
    wait $spid &>/dev/null # om vi waitar måste alla barn dö innan vi själva dör, om vi får en SIGINT eller SIGQUIT (??? källa på det). Vi fastnar i en oändlig loop av kill(sigint) till oss själva iaf (se strace)
done
