#!/bin/bash

function printStatus {
    contents="$(cat ~/.program_mode)"
    if [ "$contents" == "on" ]; then
        echo "P"
    elif [ "$contents" == "swe" ]; then
        # echo "%{F#ff6347}ÅÄÖ%{F-}"
        echo "ÅÄÖ"
    else
        echo ""
    fi
}


trap "printStatus" SIGUSR1

printStatus
while true; do
    sleep infinity &
    wait $!
done
