#!/bin/bash

set -e

function print_help {
    echo "usage:" >&2
    echo "  sxiv_zip -h" >&2
    echo "  sxiv_zip [--] zipfile | rarfile | directory" >&2
    # echo "  sxiv_zip -d [--] dir" >&2
}

while [[ "$1" ]]; do
    case "$1" in
        # -d) fold=true ;;
        -h) print_help; exit 0 ;;
        --) shift; break ;;
        *) break ;;
    esac
    shift
done

if [[ $# -ne 1 ]]; then
    echo "too many arguments? too few?" >&2
    print_help
    exit 0
fi

targ=$1
if [[ ! -e $targ ]]; then
    echo "\"$targ\" does not exist" >&2
    exit 1
fi

temp=$(mktemp -d --tmpdir 'sxiv_zip.XXXXXXXXXX')
trap 'rm -rf "$temp"' EXIT

if [[ -d $targ ]]; then
    ln -srt "$temp" "$targ"
elif [[ -f $targ ]]; then
    ext=${targ##*.}
    case ${ext,,} in
        zip|cbz)
            if command -v fuse-zip &>/dev/null; then
                trap 'fusermount -u "$temp"; rm -d "$temp"' EXIT
                if ! fuse-zip -r "$targ" "$temp"; then
                    exit 1
                fi
            elif command -v archivemount &>/dev/null; then
                trap 'umount "$temp"; rm -d "$temp"' EXIT
                if ! archivemount -o readonly "$targ" "$temp"; then
                    exit 1
                fi
            else
                if ! unzip "$targ" -d "$temp" &>/dev/null; then
                    echo "unzip failed, is this really a zip file?" >&2
                    exit 1
                fi
            fi
            ;;
        rar|cbr)
            if ! unrar x "$targ" "$temp" &>/dev/null; then
                echo "unrar failed, is this really a rar file?" >&2
                exit 1
            fi
            ;;
        *)
            echo "\"$targ\" doesn't seem to be a zip/cbz file, hmmm.." >&2
            exit 1
            ;;
    esac
else
    echo "expected a file or directory" >&2
    exit 1
fi

find -L "$temp" -type f | LC_ALL=C sort -V | sxiv -i
