#!/bin/bash

# Shows the status of the current repo in short form, unless it is detached and non-dirty.
# Shows git ahead info if an argument is given.

set -e

if [[ $# -ne 0 && $# -ne 1 ]]; then
    echo "Wrong number of arguments" >&2
    exit 1
fi

STATUS=$(git -c color.ui=always status --short --branch --ignore-submodules=dirty)
NUM_LINES=$(wc -l <<< "$STATUS")
HEADERS=1

DETACHED=true
git-not-detached && DETACHED=false

if [[ "$NUM_LINES" -gt $HEADERS ]] || ! $DETACHED; then
    git-display
    head -n $HEADERS <<< "$STATUS"
    if [[ $# -eq 1 ]] && ! $DETACHED; then
        git-ahead --blank "$1"
    fi
    tail -n +$((HEADERS+1)) <<< "$STATUS"
fi
