#!/bin/bash

# Shows the status of all submodules, unless they are detached and non-dirty

TOPLEVEL=false
if [[ "$1" == --toplevel ]]; then
    TOPLEVEL=true
fi

STATUS=$(git -c color.ui=always status --short --branch --ignore-submodules=dirty)
NUM_LINES=$(wc -l <<< "$STATUS")

if $TOPLEVEL; then
    displaypath=$(git rev-parse --show-prefix)
fi

if [[ "$NUM_LINES" -gt 1 ]] || git-detached; then
    echo -n '#'
    tput bold
    tput setaf 4
    echo " ${displaypath:-.}"
    tput sgr0
    echo "$STATUS"
fi

if $TOPLEVEL; then
    git submodule --quiet foreach --recursive "$0"
fi
