#!/bin/bash

# Runs git with a nice header displaying the current submodule

set -e

echo -n '#'
tput bold
tput setaf 4
echo " ${displaypath:-.}"
tput sgr0

# This is not a valid first argument to git, so its fine to use it as a special value.
if [[ $1 != -- ]]; then
    exec git "$@"
fi
