#!/bin/bash

# Runs a command in all submodules and the top-level repo, unlike `git submodule foreach --recursive`.

set -e

notdetached=false
isdetached=false
ignorestatus=false
doall=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        --not-detached)
            notdetached=true
            ;;
        --is-detached)
            isdetached=true
            ;;
        --ignore-fail)
            ignorestatus=true
            ;;
        --all)
            doall=true
            ;;
        *) break ;;
    esac
    shift
done

cmd=$*
if $ignorestatus; then
    cmd="$cmd || true"
fi
if $notdetached; then
    cmd="if git-not-detached; then $cmd; fi"
elif $isdetached; then
    cmd="if ! git-not-detached; then $cmd; fi"
fi
if ! $doall; then
    cmd='case "$displaypath" in ../*) true ;; *) '"$cmd"' ;; esac'
fi

displaypath=$(git rev-parse --show-cdup)
displaypath=${displaypath:-.}
export displaypath
# TODO: also add name, sm_path, sha1 and toplevel

(cd "$displaypath" && exec sh -c "$cmd" "$cmd")

export -n displaypath

git submodule --quiet foreach --recursive "$cmd"
