#!/bin/bash

source xgit-pager.bash

set -eu

# NOTE: When run as a git alias, the current working directory is changed to repo top
# level and this env var is set to where the script was actually called from.
# See man 1 git-config
cd "${GIT_PREFIX:-.}"
# NOTE: I also unset it here so further commands don't try to compensate for this too
unset -v GIT_PREFIX

TEMP=$(getopt -s bash -n xgit-foreach -o +bdiaGh -l not-detached,branch,is-detached,ignore-fail,all,no-git,help,hilfe -- "$@")
eval set -- "$TEMP"
unset TEMP

# NOTE: We don't want git to accidentally start a pager on every submodule
export GIT_PAGER=cat

print_help() {
    echo 'Usage:'
    echo ' xgit-foreach [options] [--] <command>...'
    echo
    echo 'Runs a command in all submodules and, unlike "git submodule foreach --recursive", also in the containing repo.'
    echo
    echo 'Options:'
    echo ' -b, --branch, --not-detached    The submodule must have a branch checked out for the command to run'
    echo ' -d, --is-detached               The submodule must be in detached head for the command to run'
    echo ' -i, --ignore-fail               Dont abort if the command fails'
    echo ' -a, --all                       Dont limit to only submodules in the current directory'
    echo ' -G, --no-git                    Do not prepend an implicit "git" to the command'
    echo ' -h, --help, --hilfe             Print this help message'
}

notdetached=false
isdetached=false
ignorestatus=false
doall=false
implicitgit=true
while [[ $# -gt 0 ]]; do
    case "$1" in
        --not-detached|--branch|-b)
            notdetached=true
            ;;
        --is-detached|-d)
            isdetached=true
            ;;
        --ignore-fail|-i)
            ignorestatus=true
            ;;
        --all|-a)
            doall=true
            ;;
        --no-git|-G)
            implicitgit=false
            ;;
        --help|--hilfe|-h)
            print_help
            exit
            ;;
        --)
            shift
            break
            ;;
        *)
            echo internal error >&2
            exit 1
            ;;
    esac
    shift
done

if [[ $# -eq 0 ]]; then
    echo no command given >&2
    exit 1
fi

cmd=${*@Q}
if $implicitgit; then
    cmd="xgit-foreach-print-submodule && xgit-wrapper $cmd"
fi

if $ignorestatus; then
    cmd="{ $cmd; } || true"
fi

if $notdetached && $isdetached; then
    echo incompatible options given about detached head status >&2
    exit 1
elif $notdetached; then
    cmd="if xgit-not-detached; then $cmd; fi"
elif $isdetached; then
    cmd="if ! xgit-not-detached; then $cmd; fi"
fi

if ! $doall; then
    cmd='case "$displaypath" in ../*) true ;; *) '"$cmd"' ;; esac'
fi

displaypath=$(git rev-parse --show-cdup)
displaypath=${displaypath:-.}
export displaypath
# NOTE: the other variables are intentionally not set since there are no valid values for
# them. They are not set to empty values because that could confuse the cmd. These are the
# ones: name, sm_path, sha1 and toplevel
# TODO: maybe that name could be the current repo name? What is the purpose of the name
# section in .gitmodules? Can it be different than the basename of the path?

(cd "$displaypath" && exec sh -c "$cmd")

export -n displaypath

xgit-wrapper submodule --quiet foreach --recursive "$cmd"
