#!/bin/bash

# Prints branch status in the same way as `git status --short --branch`, but the branches
# can be anything, not just the current and it's upstream.

source xgit-color.bash

set -eu

if (($# != 2)); then
    echo 'Needs two commits to compare' >&2
    exit 1
fi

function parse_argument {
    local -r _arg=$1
    local -n _rev=$2
    local -n _disp=$3

    _rev=$_arg
    _disp=$_arg

    case $_arg in
        HEAD+|HEAD++)
            _rev=HEAD
            _disp=$(git rev-parse --abbrev-ref HEAD)
            if [[ $_disp == HEAD ]]; then
                _disp="${_disp}-detached"
            fi
            ;;
        *) ;;
    esac

    case $_arg in
        HEAD++)
            if ! xgit-is-clean; then
                _disp="${_disp}-dirty"
            fi
            ;;
        *) ;;
    esac
}

left_rev=
left_disp=
parse_argument "$1" left_rev left_disp

right_rev=
right_disp=
parse_argument "$2" right_rev right_disp

aheadcol=$(xgit-color fg green)
behindcol=$(xgit-color fg red)
reset=$(xgit-color reset)

#TODO: show equal commits with --cherry-mark?
read -r ahead behind < <(git rev-list --count --left-right "$left_rev"..."$right_rev")

echo -n "${aheadcol}${left_disp}${reset}...${behindcol}${right_disp}${reset}"

if ((ahead != 0 && behind != 0)); then
    echo -n " [ahead ${aheadcol}${ahead}${reset}, behind ${behindcol}${behind}${reset}]"
elif ((ahead != 0)); then
    echo -n " [ahead ${aheadcol}${ahead}${reset}]"
elif ((behind != 0)); then
    echo -n " [behind ${behindcol}${behind}${reset}]"
fi

echo
