#!/bin/bash

# TODO: change to something that can give a graphical password prompt
SUDOPROG=sudo
HEADSET=70:26:05:0D:2E:C8
TIMEOUT=10

if [[ $1 = on ]]; then
    if ! $SUDOPROG systemctl start bluetooth; then
        notify-send 'Failed to start bluetooth.service'
        exit 1
    fi

    if ! bluetoothctl power on; then
        notify-send 'Failed to power on bluetooth'
        exit 1
    fi

    notify-send 'Connecting to headset...'
    # NOTE: the connect doesn't fail with non-zero, but info does
    if ! bluetoothctl --timeout "$TIMEOUT" connect "$HEADSET" || ! bluetoothctl info; then
        notify-send 'Failed to connect to headset'
        exit 1
    fi

    notify-send 'Bluetooth connected!'

elif [[ $1 = off ]]; then
    notify-send 'Disabling bluetooth...'
    bluetoothctl disconnect
    bluetoothctl power off
    $SUDOPROG systemctl stop bluetooth
    notify-send 'Bluetooth disabled!'

else
    echo nani? >&2
    exit 1
fi
