#!/bin/bash

# convert_to_cbz folder [folder..]
# converts each folder x of images into x.cbz with those images

set -e

if [[ $# -le 0 ]]; then
    echo "me wants some arguments :(" >&2
    exit 1
fi

for f in "$@"; do
    newname="$f.cbz"
    if [[ -e $newname ]]; then
        echo "\"$newname\" already exists, skipping..." >&2
        continue
    fi
    if [[ ! -d $f ]]; then
        echo "\"$f\" is not a directory, skipping... " >&2
        continue
    fi

    echo "creating \"$newname\"..."
    if zip -jmr "$newname" "$f" >/dev/null; then
        rm -d "$f"
        echo "done!"
    else
        echo "zipping failed, aborting..." >&2
        exit 1
    fi
done
