#!/bin/bash

set -e

if [[ $# -eq 0 ]]; then
    echo 'give me arguments plz' >&2
    exit 1
fi

RESET=$(tput sgr0)
RED=$(tput bold setaf 1)
BLUE=$(tput bold setaf 4)
YELLOW=$(tput bold setaf 3)
GREEN=$(tput bold setaf 2)

ZIP_LOG=/tmp/dir2cbz.log

for d in "$@"; do
    if [[ ! -d $d ]]; then
        echo "${YELLOW}Warning:${RESET}" "'$d' is not a directory, skipping..." >&2
        continue
    fi

    echo -n "${BLUE}Creating:${RESET} $d.cbz..."
    if ! zip -vrmT6 "$d".cbz "$d" 2>&1 | tee "$ZIP_LOG" | sed -nE 's/^total.*-> ([0-9]+)% savings$/'" ${GREEN}Reduced:${RESET} \1%"'/p'; then
        echo "${RED}Error:${RESET} zip failed, see '$ZIP_LOG'" >&2
        exit 1
    fi
done
