#!/bin/python

# pip install ewmh

import ewmh
from Xlib import X
from tabulate import tabulate
from fzf_dmenu import fzf_dmenu
import subprocess as P

def getTitle(e, w):
   return e.getWmName(w).decode() or w.get_wm_name()

def getClass(w):
   return "{}({})".format(*w.get_wm_class())

def getDesktopNames(e):
   raw = e.root.get_full_property(e.display.get_atom("_NET_DESKTOP_NAMES"), X.AnyPropertyType).value
   return [d.decode() for d in raw.split(b"\x00") if d]

def main():
   e = ewmh.EWMH()
   active = e.getActiveWindow()
   all = e.getClientList()
   names = getDesktopNames(e)
   fields = []

   i = 0
   for w in all:
      dname = names[e.getWmDesktop(w)]
      clas = getClass(w)
      if w.id == active.id:
         clas = "*" + clas
      tit = getTitle(e, w)
      fields.append((i, dname, clas, tit))
      i += 1

   tab = tabulate(fields)

   res = fzf_dmenu(tab, fzf_options=["--nth=2..", "--with-nth=2.."])

   if res:
      cind = int(res.split("  ")[0])
      # FIXME: so ugly
      P.run(["wmctrl", "-i", "-a", str(all[cind].id)])
      # e.setActiveWindow(all[cind])

if __name__ == "__main__":
   main()
