#!/bin/python

# pip install ewmh

import ewmh
from Xlib import X
import subprocess as P
from tabulate import tabulate

def getTitle(e, w):
   return e.getWmName(w).decode() or w.get_wm_name()

def getClass(w):
   return "{}({})".format(*w.get_wm_class())

def getDesktopNames(e):
   raw = e.root.get_full_property(e.display.get_atom("_NET_DESKTOP_NAMES"), X.AnyPropertyType).value
   return [d.decode() for d in raw.split(b"\x00") if d]

def main():
   e = ewmh.EWMH()
   active = e.getActiveWindow()
   all = e.getClientList()
   names = getDesktopNames(e)
   fields = []

   i = 0
   for w in all:
      dname = names[e.getWmDesktop(w)]
      clas = getClass(w)
      if w.id == active.id:
         clas = "*" + clas
      tit = getTitle(e, w)
      fields.append((i, dname, clas, tit))
      i += 1

   tab = tabulate(fields)

   res = P.run(["fzf_dmenu", "--nth=2..", "--with-nth=2.."], input=tab, text=True, stdout=P.PIPE)

   if res.stdout:
      cind = int(res.stdout.split("  ")[0])
      # FIXME: so ugly
      P.run(["wmctrl", "-i", "-a", str(all[cind].id)])
      # e.setActiveWindow(all[cind])

if __name__ == "__main__":
   main()
