#!/bin/bash

# Wrapper for a fzf that opens in a separate urxvt window:
# fzf_dmenu [fzfargs...]
# Alternate mode to interactively enter any line:
# fzf_dmenu -- [prompt] [readargs...]
# The environment variable URXVTFZF_GEOMETRY can be set to change the
# size of the terminal window.

DOCAT=false

if [[ $1 = -- ]]; then
    shift
    DOCAT=true
fi

exec {out}>&1 {inn}<&0

if $DOCAT; then
    if [[ -n $1 && ! $1 = -* ]]; then
        set -- -p "$1" "${@:2}"
    elif [[ $# -eq 0 ]]; then
        set -- -p ">> "
    fi
    cmd="read -e ${*:+$(printf "%q " "$@")} line && [ -n \"\$line\" ] && echo -E \"\$line\" 1>&$out"
else
    cmd="fzf --reverse ${*:+$(printf "%q " "$@")} 1>&$out 0<&$inn"
fi
urxvt -name URxvtFZF -geometry "${URXVTFZF_GEOMETRY:-100x24}" -e sh -c "$cmd"

exec {out}>&- {inn}<&-
