#!/bin/bash

# Wrapper for a fzf that opens in a separate terminal window:
# fzf_dmenu [fzfargs...]
# Alternate mode to interactively enter any line with filename completion:
# fzf_dmenu -- [readargs...]
# The environment variable URXVTFZF_GEOMETRY can be set to change the
# size of the terminal window.

DOCAT=false

if [[ $1 = -- ]]; then
    shift
    DOCAT=true
fi

exec {out}>&1 {inn}<&0

if $DOCAT; then
    if [[ $# -eq 0 ]]; then
        set -- -p ">> "
    fi
    # NOTE: the expansion is supposed to be delayed
    # shellcheck disable=SC2016
    cmd=(bash -c 'read -e "$@" line && printf "%s" "$line" '">&$out" '' "$@")
else
    cmd=(bash -c 'fzf --reverse "$@" '">&$out <&$inn" '' "$@")
fi

exec st -n URxvtFZF -g "${URXVTFZF_GEOMETRY:-100x24}" -e "${cmd[@]}" &>/dev/null
