#!/bin/bash

set -eu

if [[ $# -ne 2 || ! -f $1 || ! -b $2 ]]; then
    echo invalid arguments >&2
    echo usage: >&2
    echo "$0" ISO-FILE BLOCK-DEVICE >&2
    exit 1
fi

# Archwiki recommends running cat or cp followed by a sync
# https://wiki.archlinux.org/title/USB_flash_installation_medium#Using_basic_command_line_utilities.
# I don't like that approach because:
#   1. The whole ISO will most likely all end up in the cache in RAM, the command finishes
#      and the kernel is slowly writing them out to the slow drive.
#   2. I can't find any documentation that states that sync will affect direct writes to a
#      block device, the man pages only mention that it flushes filesystems. But the
#      kernel does treat the block device as any other file, and that file is on a
#      filesystem, so it probably still applies.
#   3. No progress information.
#
# So I use an approach of dd and udisksctl that both should address the above issues.
#   1. dd is used with oflag=dsync, which will wait for each write to complete before
#      doing the next read. The same effect could probably be achieved with oflag=direct, but
#      that seems even more sensitive to the block size than dsync. The block size is an
#      arbitrary large value that seems to work the best for randos on the interwebs.
#   2. conv=fsync will call fsync at the very end, so everything should be written to the
#      disk when dd is complete. There are though internal caches and stuff that some disks
#      can have, and those are probably not flushed by dd. So a power-off from udisksctl is
#      issued to flush those caches and power off the drive, so everything should be on
#      persistent storage after this! This power-off is what GUI file managers use to eject
#      drives btw. The man page for fsync(2) states that it will write through disk caches
#      if present, so the power off is maybe not strictly needed.
#   3. status=progress and oflag=dsync will make sure actual progress is displayed.

set -x

dd if="$1" \
   of="$2" \
   bs=1M \
   status=progress \
   conv=fsync \
   oflag=dsync

udisksctl power-off --block-device "$2"
