#!/bin/bash

# saves a screenshot in a directory and tries to put in the clipboard

DIRECTORY="$HOME/Pictures/screenshots"
FILENAME="$DIRECTORY/$(date '+%F_%T_%N').png"

if maim "$@" "$FILENAME"; then
    notify-send 'screenshot' "saved at $FILENAME"
else
    notify-send 'screenshot' 'failed or was aborted'
    exit 1
fi

SIZE=$(stat -c %s "$FILENAME")
if [[ $SIZE -gt 500000 ]]; then
    notify-send 'screenshot' 'too large, not available in the clipboard'
    exit 1
fi

TYPE=$(file -b --mime-type "$FILENAME")
if ! xclip -selection clipboard -t "$TYPE" -i "$FILENAME"; then
    notify-send 'screenshot' 'xclip failed to put the screenshot in the clipboard'
fi
