#!/bin/bash

DIRECTORY="$HOME/Pictures/screenshots"
HIGH="$DIRECTORY/$(date '+%F_%T_%N').png"
TEMP_DIRECTORY="${TMPDIR:-/tmp}"
LOW="$TEMP_DIRECTORY/screenshot.jpg"

if maim "$@" "$HIGH"; then
    notify-send 'screenshot' "fullres saved at $HIGH"
else
    notify-send 'screenshot' 'failed or was aborted'
    exit 1
fi

if magick "$HIGH" "$LOW"; then
    notify-send 'screenshot' "compressed version available at $LOW"
else
    notify-send 'screenshot' 'failed to create a compressed version'
    exit 1
fi

TYPE=$(file -b --mime-type "$LOW")
if ! xclip -selection clipboard -t "$TYPE" -i "$LOW"; then
    notify-send 'screenshot' 'xclip failed to put the screenshot in the clipboard'
else
    notify-send 'screenshot' 'compressed is in the clipboard'
fi
