#!/bin/bash

choice=$(man -k . | rofi -dmenu -matching regex | sed -E 's/^(.+?) \((.+?)\).*-.*$/\2 \1/')

if [[ -n $choice ]]; then
    emacsclient -n -c -e "(same-buffer (man \"$choice\"))" &>/dev/null
fi
