#!/bin/bash

choice=$(man -k . | fzf_dmenu --tiebreak=begin --prompt="man: " | sed -E 's/^([^ ]+) \(([^\)]+)\).*$/\2 \1/')

if [[ -n $choice ]]; then
    emacsclient -n -c -e "(same-buffer (man \"$choice\"))" &>/dev/null
fi
