#!/bin/bash

declare -A scripts

# TODO: vore nice ifall varje grej lade in sina egna entries här
scripts["Clipboard history"]='CM_LAUNCHER=rofi-script clipmenu "$(CM_LAUNCHER=rofi-script clipmenu | fzf_dmenu)"'
scripts["PulseAudio Volume Control"]="pavucontrol"
scripts["Kill picom"]="pkill picom"
scripts["Change theme"]="theme_selector"
scripts["Power off/save monitors"]="xset dpms force off"
scripts["Open Downloaded PDF"]='open_downloaded_pdf'
scripts["Suspend"]='systemctl suspend'
scripts['Emacs Calc']='emacsclient -n -c -e "(progn (full-calc) (calc-trail-display t))"'
scripts['Org quick todo']="fzf_dmenu -- 'Add TODO: ' | sed -E 's/^/* TODO /' >> $HOME/Documents/org/keep.org"
scripts['Org open keep.org']="emacsclient -c -n $HOME/Documents/org/keep.org"
scripts['Man']="rofi_man"
scripts['Emoji selector']='rofi_iconfont emoji "$HOME/.emoji"'
scripts['Font Awesome 4.7 selector']='rofi_iconfont awesome "$HOME/.awesome47"'
scripts['Emotion selector']='rofi_emoticon'
scripts['Mount USB drive']='usbmounter mount'
scripts['Unmount USB drive']='usbmounter unmount'
scripts['Power off USB drive']='usbmounter poweroff'
scripts['Restart Trayer']='fifoecho /tmp/statusbar_fifo TRAY'
scripts['Mount NAS']='if mount /media/NAS; then notify-send NAS nice; else notify-send NAS failed; fi'

choice=$(printf '%s\n' "${!scripts[@]}" | sort | fzf_dmenu)

if [[ "$choice" ]]; then
    # NOTE: None of these commands are long running, so they don't
    # really need to be in a new session (setsid). This script is only
    # spawned from xmonad anyway, and that runs setsid. So the forked
    # bash here has a unique session, it is just not equal to it's own
    # PID.
    eval "${scripts[$choice]}" &
fi
