#!/bin/bash

choice=$(man -k . | fzf_dmenu --prompt="man: " | sed -E 's/^([^ ]+) \(([^\)]+)\).*$/\2 \1/')

if [[ -n $choice ]]; then
    emacsclient -n -e "(popup-frame (man \"$choice\"))" &>/dev/null
fi
