#!/bin/bash

declare -A scripts

scripts["Clipboard history"]="CM_LAUNCHER=rofi clipmenu"
scripts["Invert colors"]="xrandr-invert-colors"
scripts["Toggle redshift"]="pkill -USR1 '^redshift$'"
scripts["Audio powersave toggle"]="gksudo toggle_audio_powersave"
scripts["Manjaro i3 menu"]="morc_menu"
scripts["Manjaro Settings Manager"]="manjaro-settings-manager"
scripts["PulseAudio Volume Control"]="pavucontrol"
scripts["bmenu"]="terminal -e bmenu"
scripts["Kill compton"]="pkill compton"
scripts["Start/restart compton"]="display_updater compton"
scripts["Screenshot whole screen"]="maim-notify -d 1"
scripts["Screenshot selection"]="maim-notify -su"
scripts["Screenshot clipboard whole screen"]="maim_clipboard -d 1"
scripts["Screenshot clipboard selection"]="maim_clipboard -su"
scripts["Set transparency to 99%"]="transset-df -a 0.99"
scripts["Set transparency to 100%"]="transset-df -a 1"
scripts["Program mode toggle"]="prog_mode_toggle"
scripts["Program mode swedish toggle"]="prog_mode_toggle swetoggle"
scripts["Show xtitle"]='notify-send "$(xtitle)"'
scripts["Change theme"]="theme_select_rofi"
scripts["Lock and turn off screen"]="screenmng lock"
scripts["Lock"]='screenmng lock_only'
scripts["Refresh Polybar (SIGUSR1)"]="pkill -USR1 -x polybar"
scripts["Display Updater"]="display_updater_rofi"
scripts["Open Downloaded PDF"]='open_downloaded_pdf'
scripts["Suspend"]='systemctl suspend'
scripts['Presentation Mode toggle']='screenmng toggle'
scripts['Org Agenda']='emacsclient -n -c -e '"'"'(same-buffer (org-agenda))'"'"
scripts['Org quick todo']="rofi -dmenu -p 'TODO' | sed -E 's/^/\\n* TODO /' >> $HOME/Dropbox/org/keep.org"
scripts['Org open keep.org']="emacsclient -c -n $HOME/Dropbox/org/keep.org"
scripts['Man']="rofi_man"
scripts['Emoji selector']='rofi_iconfont emoji "$HOME/.emoji"'
scripts['Font Awesome 4.7 selector']='rofi_iconfont awesome "$HOME/.awesome47"'
scripts['Window list']="rofi -show window"

choice="$( printf '%s\n' "${!scripts[@]}" | sort | rofi -dmenu -i -p "exec" -no-custom )"

if [[ "$choice" ]]; then
    echo "du valde $choice"
    eval "${scripts[$choice]}" &
else
    echo "du valde inget"
fi
