#!/bin/bash

set -e

SPEAKERS=alsa_output.pci-0000_00_1f.3.analog-surround-51
HEADPHONES=alsa_output.usb-SteelSeries_Arctis_Pro_Wireless-00.stereo-game

if [[ $# -eq 0 ]]; then
    echo fel
    exit 1
fi

function get_sink_number {
    pactl list short sinks | grep -F "$1" | cut -f1
}

function get_default_sink {
    pactl info | grep -F 'Default Sink: ' | cut -b15-
}

function get_card_number {
    pactl list sinks | awk 'BEGIN { rightsink=0 }
/^[[:blank:]]+Name: / { rightsink=($2 == "'"$1"'") }
rightsink && /alsa.card = / { print(substr($3, 2, length($3)-2)) }'
}

if [[ $1 = status ]]; then
    curr=$(get_default_sink)
    if [[ $curr = "$SPEAKERS" ]]; then
        echo S
    elif [[ $curr = "$HEADPHONES" ]]; then
        echo H
    else
        echo X
    fi
    exit
elif [[ $1 = headphones ]]; then
    pactl set-default-sink "$(get_sink_number "$HEADPHONES")"
    amixer -q -c "$(get_card_number "$HEADPHONES")" set PCM,1 100%
elif [[ $1 = speakers ]]; then
    pactl set-default-sink "$(get_sink_number "$SPEAKERS")"
fi

# update statusbar module
exec fifoecho /tmp/statusbar_fifo speakers
