#!/bin/bash

index=$HOME/.cache/watch_movie
dirs=(/media/NAS/Anime/Anime /media/NAS/filmer)

export URXVTFZF_GEOMETRY=150x38

if [[ $1 = -r ]]; then
    notify-send 'Watch Movie' 'building index'

    find "${dirs[@]}" -regextype egrep -type f -iregex '^.*\.(mkv|mp4)$' -print0 \
        | tee --output-error=exit-nopipe "$index" \
        | fzf_dmenu -d / --with-nth=-1 --read0 --print0 \
        | xargs -0rn1 mpv --no-terminal --fullscreen

    notify-send 'Watch Movie' 'index built!'
else
    fzf_dmenu -d / --with-nth=-1 --read0 --print0 < "$index" \
        | xargs -0rn1 mpv --no-terminal --fullscreen

fi
