#!/bin/bash

# create-lock-img.sh bg-image lock-icon save-location
# http://www.imagemagick.org/Usage/blur/

res=$(xrandr | sed -nE 's/^.*primary ([0-9]+x[0-9]+).*$/\1/p')
# convert "$3" -scale 10% -scale 1000% "$3"
convert "$1" -resize "$res!" -blur 0x6 "$2" -gravity center -composite -matte png:"$3"
