#!/bin/bash

# generates a theme folder

set -e

# the picture should already be in the folder
pic="$(find "$1" -type f -printf '%P\n' | head -n1)"

# default to black conky
echo "#!/bin/bash" > "$1/conky"
echo "conky_start -n metro -t black &" >> "$1/conky"
echo "conky_start -n system -t black &" >> "$1/conky"
chmod +x "$1/conky"

# generate feh script
echo -e '#!/bin/bash\nfeh --bg-fill "$HOME/themes'"/$1/$pic"'"' > "$1/feh"
chmod +x "$1/feh"

# specify lock picture
ln -s "$pic" "$1/lock"
