#!/bin/bash

choice=$( (echo "random"; theme_select list-all) | fzf_dmenu --prompt="theme: ")

if [[ "$choice" = "random" ]]; then
    theme_select random
elif [[ "$choice" ]]; then
    theme_select apply "$choice"
fi
