#!/bin/bash

THEME_DIR=$HOME/themes
STATE_DIR=$THEME_DIR/__state__
PID_FILE=$STATE_DIR/.loop.pid

if [[ "$1" = --kill ]]; then
    pkill -F "$PID_FILE"
    exit
fi

if [[ $# -lt 2 ]]; then
    echo invalid usage >&2
    exit 1
fi

echo $$ > "$PID_FILE"

delay=$1
shift

trap 'jobs -p | xargs -r kill' EXIT
while true; do
    theme_select "$@"
    sleep "$delay"
done
