#!/bin/bash

choice=$( (echo "random"; theme_select -l) | fzf_dmenu --prompt="theme: ")

if [[ "$choice" = "random" ]]; then
    theme_select -r
elif [[ "$choice" ]]; then
    theme_select "$choice"
fi
