#!/bin/bash

set -e

theme_dir=$HOME/themes
cur_theme_file=$theme_dir/.theme_select_cur
fair_state=$theme_dir/.fair_state

if [[ ! -d "$theme_dir" ]]; then
    echo "$theme_dir doesn't exist!" >&2
    exit 1
fi

function set_theme {
    local cur=$theme_dir/$1
    if ! [[ -d $cur ]]; then
        echo "$1 is not a directory" >&2
        exit 1
    fi
    echo "$1" > "$cur_theme_file"

    pic=$(find -L "$cur" -type f -print -quit)
    if [[ -z $pic ]]; then
        echo "no pic in $cur" >&2
        exit 1
    fi
    feh --bg-fill "$pic"

    if [[ -z $theme_select_no_lock ]]; then
        create-lock-img "$pic" "$theme_dir/lock.png" "$HOME/.lock" &
    fi
}

function num_screens {
    xrandr | grep -cE '\bconnected\b'
}

function list_themes {
    find -L "$theme_dir" -mindepth 1 -maxdepth 1 -type d "$@"
}

function list_themes_skip_hidden {
    list_themes \! -name '_*' "$@"
}

function list_themes_files {
    find "$theme_dir" -mindepth 2 -type f "$@"
}

function list_themes_files_skip_hidden {
    list_themes_files \! -path "$theme_dir"/'_*' "$@"
}

loopsleep=
if [[ $1 = --loop ]]; then
    loopsleep=$2
    shift 2
fi

case $1 in
    -r)
        cur_theme=
        if [[ -f "$cur_theme_file" ]]; then
            read -r cur_theme < "$cur_theme_file"
        fi
        set_theme "$(list_themes_skip_hidden -printf '%f\n' | sed "/^$cur_theme$/d" | shuf -n1)"
        ;;
    --mr)
        list_themes_files_skip_hidden -print0 | shuf -z | xargs -r0 feh --bg-fill
        if [[ -z $theme_select_no_lock ]]; then
            list_themes_files -print0 | shuf -zn1 | xargs -r0I% create-lock-img % "$theme_dir/lock.png" "$HOME/.lock" &
        fi
        ;;
    --fr)
        ns=$(num_screens)
        if [[ ! -s $fair_state ]]; then
            list_themes_files_skip_hidden -print | shuf > "$fair_state"
        fi
        num_state=$(wc -l < "$fair_state")
        if [[ $num_state -lt $ns ]]; then
            tmpfile=$(mktemp -p.)
            sort "$fair_state" > "$tmpfile"
            comm -31 "$tmpfile" <(list_themes_files_skip_hidden -print | sort) | shuf >> "$fair_state"
            rm "$tmpfile"
        fi
        head -n "$ns" "$fair_state" | xargs -rd'\n' feh --bg-fill
        sed -i "1,${ns}d" "$fair_state"
        ;;
    -l)
        list_themes -printf '%f\n'
        ;;
    ""|--reapply)
        if [[ -x "$HOME"/.fehbg ]]; then
            exec "$HOME"/.fehbg
        fi
        ;;
    safe)
        set_theme safe
        pkill --exact theme_select
        ;;
    *)
        set_theme "$1"
        ;;
esac

if [[ -n $loopsleep ]]; then
    sleep "$loopsleep"
    export theme_select_no_lock=t
    exec theme_select --loop "$loopsleep" "$@"
fi
