#!/bin/bash

set -e

theme_dir=$HOME/themes
cur_theme_file=$HOME/.theme_select_cur

if [[ ! -d "$theme_dir" ]]; then
    echo "$theme_dir doesn't exist!" >&2
    exit 1
fi

function set_theme {
    local cur=$theme_dir/$1
    if ! [[ -d $cur ]]; then
        echo "$1 is not a directory" >&2
        exit 1
    fi
    echo "$1" > "$cur_theme_file"

    pic=$(find -L "$cur" -type f -print -quit)
    if [[ -z $pic ]]; then
        echo "no pic in $cur" >&2
        exit 1
    fi
    feh --bg-fill "$pic"

    if [[ -z $theme_select_no_lock ]]; then
        create-lock-img "$pic" "$theme_dir/lock.png" "$HOME/.lock" &
    fi
}

function list_themes {
    find -L "$theme_dir" -mindepth 1 -maxdepth 1 -type d "$@" -printf '%f\n'
}

loopsleep=
if [[ $1 = --loop ]]; then
    loopsleep=$2
    shift 2
fi

case $1 in
    -r)
        cur_theme=
        if [[ -f "$cur_theme_file" ]]; then
            read -r cur_theme < "$cur_theme_file"
        fi
        set_theme "$(list_themes \! -name '_*' | sed "/^$cur_theme$/d" | shuf -n1)"
        ;;
    --mr)
        find "$theme_dir" -mindepth 2 -type f \! -path "$theme_dir"/'_*' -print0 | shuf -z | xargs -r0 feh --bg-fill
        if [[ -z $theme_select_no_lock ]]; then
            find "$theme_dir" -mindepth 2 -type f -print0 | shuf -zn1 | xargs -r0I% create-lock-img % "$theme_dir/lock.png" "$HOME/.lock" &
        fi
        ;;
    -l)
        list_themes
        ;;
    ""|--reapply)
        if [[ -x "$HOME"/.fehbg ]]; then
            exec "$HOME"/.fehbg
        fi
        ;;
    safe)
        set_theme safe
        pkill --exact theme_select
        ;;
    *)
        set_theme "$1"
        ;;
esac

if [[ -n $loopsleep ]]; then
    sleep "$loopsleep"
    export theme_select_no_lock=t
    exec theme_select --loop "$loopsleep" "$@"
fi
