#!/bin/sh

if [ $# -ne 1 ]; then
    echo 'Usage: qutebrowser_cookies <DOMAIN>' >&2
    exit 1
fi

export QUTE_FIFO=/dev/null
exec "$HOME/.config/qutebrowser/userscripts/print_cookies" \
     "$HOME/.local/share/qutebrowser/webengine/Cookies" \
     "$1"
