#!/bin/bash

USERAGENT=/tmp/qutebrowser_nhentai_user_agent
COOKIES=/tmp/qutebrowser_nhentai_cookies
UA=

if [ ! -f $COOKIES ]; then
    echo 'Fetching cookies...'
    qutebrowser_cookies .nhentai.net > "$COOKIES"
fi

if [ ! -f $USERAGENT ]; then
    echo 'Fetching user agent...'
    qutebrowser_user_agent > "$USERAGENT"
fi

UA=$(cat "$USERAGENT")

exec gallery-dl \
     --cookies "$COOKIES" \
     -o user-agent="$UA" \
     --option 'filename={num:>03}.{extension}' \
     --option 'directory=["{category}", "{gallery_id} {title[:128]}"]' \
     "$@"
